up:
    docker-compose up --build

down:
    docker-compose down

logs:
    docker-compose logs -f api

bash:
    docker exec -it workout_api /bin/bash

psql:
    docker exec -it workout_db psql -U postgres -d workout_db
