"""init_db

Revision ID: 38917fd59ea3
Revises: b30437cf8423
Create Date: 2025-11-03 16:33:48.942320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision: str = '38917fd59ea3'
down_revision: Union[str, Sequence[str], None] = 'b30437cf8423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centros_treinamento', sa.Column('created_at', sa.DateTime(), server_default=func.now(), nullable=False))
    op.drop_column('centros_treinamento', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centros_treinamento', sa.Column('create_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('centros_treinamento', 'created_at')
    # ### end Alembic commands ###
