"""init_db

Revision ID: b30437cf8423
Revises: 375a8ed3e282
Create Date: 2025-11-03 16:15:14.645736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision: str = 'b30437cf8423'
down_revision: Union[str, Sequence[str], None] = '375a8ed3e282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'centros_treinamento', 
        sa.Column('create_at', sa.DateTime(), server_default=func.now(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('centros_treinamento', 'create_at')
    # ### end Alembic commands ###
